# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH

HISTFILE=~/.zsh_history
HISTSIZE=10000
SAVEHIST=10000
setopt APPEND_HISTORY # Append history instead of overwriting
setopt HIST_IGNORE_DUPS # Ignore duplicate commands
setopt HIST_REDUCE_BLANKS # Remove superfluous blanks

# User configuration

if [ -n "$DESKTOP_SESSION" ];then
    export GNOME_KEYRING_CONTROL=/run/user/$(id -u)/keyring
    export SSH_AUTH_SOCK=/run/user/$(id -u)/keyring/ssh
else
    eval `keychain --quiet --eval --agents ssh id_rsa`
fi


# export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# Keybindings
# Use emacs mode
bindkey -e

# Colours
# Enable colour output for ls
autoload -U colors && colors

# Use colour with ls
alias ls='ls --color=auto'  # For GNU ls
# Or for macOS BSD ls:
# alias ls='ls -G'

# Optional: colourized grep, etc.
alias grep='grep --color=auto'


# WSL2 config to open a Windows browser from the terminal
export BROWSER=wslview

# Set starship path:
export STARSHIP_CONFIG=~/.config/starship/starship.toml

fpath+=~/.zfunc
autoload -Uz compinit && compinit

# Enable tab completion menu
zstyle ':completion:*' menu select

# support cd ...
cd-dot() {
  if [[ "$1" == .* && "$1" != *[^.]* ]]; then
    local depth=${#1}
    local -a parts=()
    for ((i=1; i<depth; i++)); do
      parts+=("..")
    done
    builtin cd "${(j:/:)parts}"
  else
    builtin cd "$@"
  fi
}

alias cd='cd-dot'

alias setxb="setxkbmap -layout us -option ctrl:nocaps"

# `command emacs` with run the gui version
alias emacs='emacs -nw'

export PATH="$HOME/.cache/.wasm-pack/.wasm-bindgen-cargo-install-0.2.84/bin:$PATH"
export PATH="$HOME/.rbenv/bin:$PATH"
export PATH="$PATH:/$HOME/.flora/bin"
eval "$(rbenv init -)"
export PATH="$HOME/.rbenv/plugins/ruby-build/bin:$PATH"
export PATH="$PATH:/opt/mssql-tools18/bin"
export PATH="$HOME/.local/bin:$PATH"
export PATH="$HOME/.dotnet/tools:$PATH"
export PATH="$PATH:/opt/nvim-linux-x86_64/bin"
export EDITOR="vim"

export PYENV_ROOT="$HOME/.pyenv"
[[ -d $PYENV_ROOT/bin ]] && export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"


eval "$(uv generate-shell-completion zsh)"
eval "$(uvx --generate-shell-completion zsh)"
eval "$(starship init zsh)"

